apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: catalog-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          
          resources:
            requests:
              memory: "128Mi" 
              cpu: "100m"
            limits:
              memory: "256Mi" 
              cpu: "500m" 
              
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          envFrom:
            - configMapRef:
                name: catalog-config
          env:
            - name: bus__password
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: bus__password